info:
  app:
    name: ${spring.application.name}
    description:  '@application.description@'
    version: '@application.version@'
    group: '@application.group@'
    gitCurrentBranch: '@application.current.branch@'
    gitChangeSet: '@application.latest.revision@'
    buildDate: '@application.timestamp@'
    component: emarket
    category: emarket
    restApi: true
    usingDatabase: true

management:
  security:
    enabled: false

endpoints:
  spring:
    cloud:
      bus:
        env:
          enabled: true
        refresh:
          enabled: true
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logger:
  json:
    masker:
      fieldNames: cardNumber,password

spring:
  application:
    name: emarket
  profiles:
    active: local
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:h2:file:~/mbsDb
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''
    connectionTimeout: 30000
    maxLifetime: 28000000
    maximumPoolSize: 10
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
  jpa:
    database: h2
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  h2:
    console:
      enabled: true
      path: /h2-console


liquibase:
  contexts: local
  change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  config: classpath:logback.xml

server:
  port: 8221
